# Use `just work day-01 part1` to work on the specific binary for a specific day's problems

#Before use: cargo install cargo-nextest cargo-generate cargo-watch

# use PowerShell instead of sh:
set shell := ["powershell.exe", "-c"]

hello:
  Write-Host "Hello, world!"


#-s "just lint {{day}}"
work day part:
    cargo watch -w {{day}} -x "check -p {{day}}" -s "just test {{day}} {{part}}" -s "just lint {{day}}"
solve day part:
    cargo run -p {{day}} --bin {{part}} --release
www-watch:
   RUST_LOG=info cargo +nightly leptos watch --project www
www-build:
   cargo +nightly leptos build --project www --release
lint day:
    cargo clippy -p {{day}}
test day part:
    cargo nextest run -p {{day}} {{part}}
bench-all:
    cargo bench -q > benchmarks.txt
bench day part:
    cargo bench --bench {{day}} {{part}} >> {{day}}.bench.txt
flamegraph day part:
    cargo flamegraph --profile flamegraph --root --package {{day}} --bin {{part}} -o flamegraphs/{{day}}--{{part}}.svg
dhat day part:
    cargo run --profile dhat --features dhat-heap --package {{day}} --bin {{part}}
create day:
    cargo generate --git https://github.com/Renan-TP/advent-of-code.git --branch template --name {{day}}
    (Get-Content {{day}}/src/bin/part1.rs) -replace 'use ::part1::process;', 'use {{day}}::part1::process;' | Set-Content {{day}}/src/bin/part1.rs
    (Get-Content {{day}}/src/bin/part2.rs) -replace 'use ::part2::process;', 'use {{day}}::part2::process;' | Set-Content {{day}}/src/bin/part2.rs