
[package]
name = "day-16"
version = "0.1.0"
edition = "2021"

[dependencies]
nom = { workspace = true }
nom-supreme = { workspace = true }
num = { workspace = true }
itertools = { workspace = true }
# bevy.workspace = true
glam.workspace = true

[dev-dependencies]
rstest.workspace = true
